### PR TITLE
A bunch of commits

### PR DESCRIPTION
**Pull request by russplaysguitar**
Check these out and let us know if you have any questions!

### CODE REVIEW

**Comment by nyxtom** [comment]
Cool! I definitely am taking a look at all of this

**Comment by russplaysguitar** [comment]
Thanks!

**Comment by nyxtom** [comment]
Definitely, very neat work so far :) Cool open source team you guys have organized too.

**Comment by russplaysguitar** [comment]
Glad you like the changes. Thanks for creating a fun open-source project for us to work on. 

You're welcome to join the team as a remote member if you'd like? We'll be working on a new project every week. This week we're working on a Tetris clone written in Coffeescript.

**Pull request merged**
